### ISSUE TITLE
There is a problem with GzDoom 10.0. Its not working.

### ISSUE THREAD

**Issue by ihategithub5** [MajorCooke/AEoDDat#63]
Tried downloading dat file from here ,but Return type UInt4 mismatch with SInt4
Script error, "AEoDdat.pk3:zaeod/weaponswitch.txt" line 67:
Return type mismatch.

**Comment by MajorCooke** [comment]
Try using a devbuild from GZDoom. I think that was fixed.

**Comment by MajorCooke** [comment]
Closing this from lack of response.
